import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../../api";
import { ios, fontStyle } from "../../ui/iosTheme";

export const useS = () =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: COLORS.bg },
    iconBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: COLORS.surface,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: COLORS.border,
      ...ios.shadow.card,
    },
    deskTopRight: { position: "absolute", top: 24, right: 32, zIndex: 10 },
    center: { flex: 1, alignItems: "center", justifyContent: "center" },
    scroll: { padding: ios.spacing.lg, paddingBottom: ios.spacing.xxxl },
    scrollWide: { padding: ios.spacing.xxxl, maxWidth: 1200, alignSelf: "center", width: "100%" },

    hero: { paddingHorizontal: 4 },
    heroBg: {
      marginBottom: ios.spacing.xxl,
      borderRadius: ios.radius.xl,
      padding: ios.spacing.xxxl,
      borderWidth: 1,
      borderColor: COLORS.border,
      backgroundColor: COLORS.surface,
      ...ios.shadow.elevated,
      ...Platform.select({
        web: {
          backgroundImage: `linear-gradient(135deg, ${COLORS.primary}0D 0%, ${COLORS.surface} 100%)`,
        } as any,
        default: { backgroundColor: COLORS.primarySoft },
      }),
    },
    heroGreet: {
      ...fontStyle("title3"),
      color: COLORS.textSecondary,
    },
    heroName: {
      ...fontStyle("hero"),
      color: COLORS.text,
      marginTop: ios.spacing.xs,
    },
    heroDate: {
      ...fontStyle("footnote"),
      color: COLORS.textDisabled,
      marginTop: ios.spacing.md,
    },

    sectionTitle: {
      ...fontStyle("section"),
      color: COLORS.textSecondary,
      marginBottom: ios.spacing.md,
      marginLeft: 4,
    },

    tilesGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: ios.spacing.md,
    },
    tilesGridWide: {
      gap: ios.spacing.xl,
    },

    tile: {
      width: "30.5%",
      backgroundColor: COLORS.surface,
      borderRadius: ios.radius.lg,
      padding: ios.spacing.md,
      alignItems: "center",
      justifyContent: "center",
      minHeight: 105,
      borderWidth: 1,
      borderColor: COLORS.border,
      ...ios.shadow.card,
    },
    tileWide: {
      width: "23%",
      padding: ios.spacing.xl,
      minHeight: 130,
      alignItems: "flex-start",
      justifyContent: "space-between",
    },
    tileIcon: {
      width: 42,
      height: 42,
      borderRadius: ios.radius.md,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: ios.spacing.sm,
    },
    tileIconWide: {
      width: 46,
      height: 46,
      borderRadius: ios.radius.md,
      marginBottom: 0,
    },
    tileTitle: {
      ...fontStyle("subhead"),
      color: COLORS.text,
      textAlign: "center",
    },
    tileTitleWide: {
      ...fontStyle("title3"),
      textAlign: "left",
      marginTop: ios.spacing.lg,
      width: "100%",
    },

    notesContainer: {
      marginTop: ios.spacing.xxxl,
      paddingHorizontal: 4,
    },
    notesTitle: {
      ...fontStyle("section"),
      color: COLORS.textSecondary,
      marginBottom: ios.spacing.md,
    },
    noteCard: {
      backgroundColor: COLORS.surface,
      borderRadius: ios.radius.md,
      padding: ios.spacing.md,
      marginBottom: ios.spacing.sm,
      borderWidth: 1,
      borderColor: COLORS.border,
      flexDirection: "row",
      alignItems: "center",
      gap: ios.spacing.md,
      ...ios.shadow.card,
    },
    noteIconCircle: {
      width: 40,
      height: 40,
      borderRadius: ios.radius.sm,
      backgroundColor: COLORS.pendingBg,
      alignItems: "center",
      justifyContent: "center",
    },
    noteTextContainer: { flex: 1 },
    noteHeading: { ...fontStyle("bodyEmphasized"), color: COLORS.text },
    noteContent: { ...fontStyle("callout"), color: COLORS.textSecondary, marginTop: 2 },
    noteLink: { ...fontStyle("footnote"), color: COLORS.primary, marginTop: 4, fontWeight: "600" },

    dashRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    dashCard: {
      flex: 1, minWidth: 90, padding: 8, borderRadius: 8,
      alignItems: "center", gap: 4, backgroundColor: COLORS.surface,
      borderWidth: 1, borderColor: COLORS.border,
    },
    dashVal: { fontSize: 20, fontWeight: "900", color: COLORS.text },
    dashLbl: { fontSize: 10, color: COLORS.textSecondary, fontWeight: "600", textAlign: "center" },
    sectionSub: {
      fontSize: 11, fontWeight: '700', color: COLORS.textSecondary,
      textTransform: "uppercase", letterSpacing: 0.5, marginTop: 4,
    },
    hourRow: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 4 },
    hourName: { fontSize: 13, fontWeight: "600", color: COLORS.text },
    hourVal: { fontSize: 13, fontWeight: "800", color: COLORS.text, minWidth: 45, textAlign: "right" },
    hourCount: { fontSize: 12, color: COLORS.textSecondary, minWidth: 35 },
    hourBar: { height: 10, backgroundColor: COLORS.borderInput, borderRadius: 8, overflow: "hidden" },
    hourFill: { height: 10, borderRadius: 8 },

    dashStripRow: { flexDirection: "row", gap: 8, paddingHorizontal: 4 },
    dashMiniCard: {
      flex: 1, padding: 14, borderRadius: 8,
      backgroundColor: COLORS.surface, alignItems: "center", gap: 8,
      borderWidth: 1, borderColor: COLORS.border,
    },
    dashMiniIcon: {
      width: 36, height: 36, borderRadius: 18,
      alignItems: "center", justifyContent: "center",
    },
    dashMiniVal: { fontSize: 20, fontWeight: "900", color: COLORS.text },
    dashMiniLbl: { fontSize: 12, fontWeight: "600", color: COLORS.textSecondary, textAlign: "center" },

    statusBarWrap: { paddingHorizontal: 4 },
    statusBar: { height: 12, borderRadius: 8, flexDirection: "row", overflow: "hidden", marginBottom: 10 },
    statusBarSegment: { height: 12, minWidth: 1 },
    statusLegend: { flexDirection: "row", flexWrap: "wrap", gap: 10, paddingHorizontal: 4 },
    statusLegendItem: { flexDirection: "row", alignItems: "center", gap: 4 },
    statusLegendDot: { width: 8, height: 8, borderRadius: 4 },
    statusLegendText: { fontSize: 12, fontWeight: '400', color: COLORS.textSecondary },
    statusLegendCount: { fontSize: 12, fontWeight: "700", color: COLORS.text },

    overHoursBubble: {
      minWidth: 24, height: 24, borderRadius: 20,
      backgroundColor: COLORS.errorBg,
      alignItems: "center", justifyContent: "center",
      paddingHorizontal: 8,
    },
    overHoursBubbleText: { fontSize: 12, fontWeight: "800", color: COLORS.errorText },
    overHoursRow: { gap: 8, paddingHorizontal: 4 },
    overHoursItem: { backgroundColor: COLORS.surface, borderRadius: 8, padding: 12 },

    monthScroll: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingHorizontal: 8 },
    monthMiniCard: {
      width: 68, padding: 10, borderRadius: 8,
      backgroundColor: COLORS.surface, alignItems: "center", gap: 4,
      borderWidth: 2, borderColor: "transparent",
      ...ios.shadow.card,
    },
    monthMiniCurrent: { borderColor: COLORS.primary },
    monthMiniMonth: { fontSize: 9, fontWeight: "700", color: COLORS.textSecondary, textTransform: "uppercase" },
    monthMiniCount: { fontSize: 22, fontWeight: "900", color: COLORS.text },
    monthMiniHours: { fontSize: 9, fontWeight: "500", color: COLORS.textDisabled },

    cardWrap: {
      backgroundColor: COLORS.surface,
      borderRadius: 20,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: COLORS.border,
      ...ios.shadow.card,
    },
    cardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    cardTitle: { fontSize: 15, fontWeight: '600', color: COLORS.text },
    cardSubtitle: { fontSize: 12, color: COLORS.textDisabled, marginTop: 4 },
    kpiStrip: { flexDirection: "row", gap: 12, marginBottom: 16 },
    kpiCard: {
      flex: 1, backgroundColor: COLORS.surface,
      borderRadius: 16, padding: 16,
      borderWidth: 1, borderColor: COLORS.border,
      ...ios.shadow.card,
    },
    kpiIconCircle: {
      width: 44, height: 44, borderRadius: 10,
      alignItems: "center", justifyContent: "center",
      marginBottom: 12,
    },
    kpiValue: { fontSize: 30, fontWeight: "900", color: COLORS.text, letterSpacing: -0.5 },
    kpiLabel: { fontSize: 12, fontWeight: "600", color: COLORS.textSecondary, marginTop: 4 },
    donutContainer: { alignItems: "center", flexDirection: "row", gap: 20 },
    donutLegend: { flex: 1, gap: 8 },
    donutLegendItem: { flexDirection: "row", alignItems: "center", gap: 8 },
    donutLegendDot: { width: 10, height: 10, borderRadius: 4 },
    donutLegendText: { fontSize: 12, fontWeight: "600", color: COLORS.textSecondary, flex: 1 },
    donutLegendCount: { fontSize: 12, fontWeight: "800", color: COLORS.text },
    circularProgressWrap: { alignItems: "center", marginBottom: 16 },
  } as Record<string, any>);
